### PR TITLE
merge item business intel and test fixes to master

### LINKED ISSUE #43: returns top items ranked by total revenue generated

### LINKED ISSUE #44: returns top item instances ranked by total number sold

### LINKED ISSUE #45: returns the date with the most sales for a given item, using the invoice date

### LINKED ISSUE #48: Update Unit price
turn cents into $ w/ float & string

### PR DESCRIPTION
**Pull request by bermannoah**
close #48 - fix unit price issue
close #43 - top items by total revenue
close #44 - top item by instances sold
close #45 - date for most sales by given item

@AliSchlereth

### CODE REVIEW

File: app/controllers/api/v1/items/search_controller.rb [hunk 1]
```diff
@@ -6,8 +6,14 @@ def index
 
   def show
     if params[:unit_price]
```
Comment (AliSchlereth) [inline app/controllers/api/v1/items/search_controller.rb:8]: Let's refactor this on the next go-round.

**Comment by AliSchlereth** [comment]
Wooooo!
